# vi: set ft=ruby :

$script = <<SCRIPT

# switch Ubuntu download mirror to German server
sudo sed -i 's,http://us.archive.ubuntu.com/ubuntu/,http://ftp.fau.de/ubuntu/,' /etc/apt/sources.list
sudo sed -i 's,http://security.ubuntu.com/ubuntu,http://ftp.fau.de/ubuntu,' /etc/apt/sources.list
sudo apt-get update -y

# switch to German keyboard layout
sudo sed -i 's/"us"/"de"/g' /etc/default/keyboard
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y console-common
sudo install-keymap de

# set timezone to German timezone
echo "Europe/Berlin" | sudo tee /etc/timezone
sudo dpkg-reconfigure -f noninteractive tzdata

# install java
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
sudo apt-get -y upgrade
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections 
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get -y install oracle-java8-installer

# install node & js tools
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get -y update
sudo apt-get -y install nodejs
sudo npm install -g grunt-cli
sudo npm install -g bower
sudo npm install -g tsd

# install git and clone webapp-tutorial
sudo apt-get install -y git
cd /home/vagrant
git clone https://github.com/toedter/webapp-tutorial.git
sudo chown -R vagrant:vagrant .npm
cd webapp-tutorial
./gradlew prepareJS
./gradlew build

sudo apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
sudo apt-get install gnome-icon-theme-full tango-icon-theme
sudo echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

# install chrome
sudo apt-get install -y chromium-browser

# install IntelliJ IDEA  
sudo wget -O /opt/ideaIU-15.0.tar.gz http://download.jetbrains.com/idea/ideaIU-15.0.tar.gz
cd /opt/ && sudo tar -zxvf ideaIU-15.0.tar.gz
sudo rm ideaIU-15.0.tar.gz

SCRIPT


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true  
     vb.memory = "8192"
  end
  
  config.vm.provision "shell", inline: $script, privileged: false
end
