# vi: set ft=ruby :

$script = <<SCRIPT

# switch Ubuntu download mirror to German server
sudo sed -i 's,http://us.archive.ubuntu.com/ubuntu/,http://ftp.fau.de/ubuntu/,' /etc/apt/sources.list
sudo sed -i 's,http://security.ubuntu.com/ubuntu,http://ftp.fau.de/ubuntu,' /etc/apt/sources.list

# add repos and update
sudo add-apt-repository -y ppa:webupd8team/java
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo add-apt-repository ppa:xubuntu-dev/xfce-4.12
sudo apt-get -y update

# switch to German keyboard layout
sudo sed -i 's/"us"/"de"/g' /etc/default/keyboard
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y console-common
sudo install-keymap de

# set timezone to German timezone
#echo "Europe/Berlin" | sudo tee /etc/timezone
#sudo dpkg-reconfigure -f noninteractive tzdata

# install node & js tools
sudo apt-get install -y nodejs

# install java
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get -y install oracle-java8-installer

# install git and clone webapp-tutorial
sudo apt-get install -y git
cd /home/vagrant
git clone https://github.com/toedter/webapp-tutorial.git
sudo chown -R vagrant:vagrant .npm
cd webapp-tutorial

./gradlew prepareJS build --console plain
# with http proxy
#./gradlew -Dhttp.proxyHost=194.145.60.1 -Dhttp.proxyPort=9400 -Dhttps.proxyHost=194.145.60.1 -Dhttps.proxyPort=9400 prepareJS build --console plain

# install xfce
sudo apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
sudo apt-get install gnome-icon-theme-full tango-icon-theme
sudo echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

# install chrome
sudo apt-get install -y chromium-browser

# install IntelliJ IDEA  
sudo wget -O /opt/ideaIU-2018.1-no-jdk.tar.gz https://download.jetbrains.com/idea/ideaIU-2018.1-no-jdk.tar.gz
cd /opt/ && sudo tar -zxvf ideaIU-2018.1-no-jdk.tar.gz
sudo rm /opt/ideaIU-2018.1-no-jdk.tar.gz
sudo chown -R vagrant:vagrant .

SCRIPT


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # config.proxy.http     = "http://194.145.60.1:9400"
  # config.proxy.https    = "http://194.145.60.1:9400"
  # config.proxy.no_proxy = "localhost,127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "webapp-tutorial"
     vb.gui = true  
     vb.memory = "4096"
     vb.cpus = 2
     vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
  
  config.vm.provision "shell", inline: $script, privileged: false
end
